In [52]:
import cv

ModuleNotFoundError: No module named 'cv'

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import RidgeClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# READ DATA

In [2]:
file = '/Users/pd186029/Documents/Pranay/Teradata/Development/full_stck/data_jarvis_data/spaceship_titanic/spaceship-titanic/train.csv'

In [3]:
df = pd.read_csv(file,sep=',')
df.head(3)

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck             Name  \
0          0.0        0.0           0.0     0.0     0.0  Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0     Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0    Altark Susent   

   Transported  
0        False  
1         True  
2        False

In [4]:
df['PassengerId'].astype('float')


0          101.0
1          201.0
2          301.0
3          302.0
4          401.0
          ...   
8688    927601.0
8689    927801.0
8690    927901.0
8691    928001.0
8692    928002.0
Name: PassengerId, Length: 8693, dtype: float64

In [5]:
pd.to_numeric(df['RoomService'])

0         0.0
1       109.0
2        43.0
3         0.0
4       303.0
        ...  
8688      0.0
8689      0.0
8690      0.0
8691      0.0
8692    126.0
Name: RoomService, Length: 8693, dtype: float64

In [6]:
df.iloc[97]

PassengerId            0103_03
HomePlanet               Earth
CryoSleep                 True
Cabin                   G/18/S
Destination        TRAPPIST-1e
Age                        6.0
VIP                      False
RoomService                0.0
FoodCourt                  0.0
ShoppingMall               0.0
Spa                        0.0
VRDeck                     0.0
Name            Fanne Mclainez
Transported              False
Name: 97, dtype: object

In [48]:
lst = [1,2]
str(lst)

'[1, 2]'

# DATA Exploration

#check numeric values
#Check for zero variance
#Check missing values or strange values (example Age min is 0)

In [7]:
df.describe()

Age   RoomService     FoodCourt  ShoppingMall           Spa  \
count  8514.000000   8512.000000   8510.000000   8485.000000   8510.000000   
mean     28.827930    224.687617    458.077203    173.729169    311.138778   
std      14.489021    666.717663   1611.489240    604.696458   1136.705535   
min       0.000000      0.000000      0.000000      0.000000      0.000000   
25%      19.000000      0.000000      0.000000      0.000000      0.000000   
50%      27.000000      0.000000      0.000000      0.000000      0.000000   
75%      38.000000     47.000000     76.000000     27.000000     59.000000   
max      79.000000  14327.000000  29813.000000  23492.000000  22408.000000   

             VRDeck  
count   8505.000000  
mean     304.854791  
std     1145.717189  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%       46.000000  
max    24133.000000

#check categorical values
#Check frequency. Very high frequency is not reqired (example Cabin). Or can be converted to aggregate features
#Check missing values or strange values (example Age min is 0)

In [8]:
df.describe(include='object') 

PassengerId HomePlanet CryoSleep    Cabin  Destination    VIP  \
count         8693       8492      8476     8494         8511   8490   
unique        8693          3         2     6560            3      2   
top        0001_01      Earth     False  G/734/S  TRAPPIST-1e  False   
freq             1       4602      5439        8         5915   8291   

                  Name  
count             8493  
unique            8473  
top     Gollux Reedall  
freq                 2

In [7]:
df.isnull()

PassengerId  HomePlanet  CryoSleep  Cabin  Destination    Age    VIP  \
0           False       False      False  False        False  False  False   
1           False       False      False  False        False  False  False   
2           False       False      False  False        False  False  False   
3           False       False      False  False        False  False  False   
4           False       False      False  False        False  False  False   
...           ...         ...        ...    ...          ...    ...    ...   
8688        False       False      False  False        False  False  False   
8689        False       False      False  False        False  False  False   
8690        False       False      False  False        False  False  False   
8691        False       False      False  False        False  False  False   
8692        False       False      False  False        False  False  False   

      RoomService  FoodCourt  ShoppingMall    Spa  VRDeck   Name  Transported  
0           False      False         False  False   False  False        False  
1           False      False         False  False   False  False        False  
2           False      False         False  False   False  False        False  
3           False      False         False  False   False  False        False  
4           False      False         False  False   False  False        False  
...           ...        ...           ...    ...     ...    ...          ...  
8688        False      False         False  False   False  False        False  
8689        False      False         False  False   False  False        False  
8690        False      False         False  False   False  False        False  
8691        False      False         False  False   False  False        False  
8692        False      False         False  False   False  False        False  

[8693 rows x 14 columns]

In [53]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [54]:
list(df.isnull().sum())

[0, 201, 217, 199, 182, 179, 203, 181, 183, 208, 183, 188, 200, 0]

In [56]:
pd.DataFrame(df.isnull().sum().reset_index())

index    0
0    PassengerId    0
1     HomePlanet  201
2      CryoSleep  217
3          Cabin  199
4    Destination  182
5            Age  179
6            VIP  203
7    RoomService  181
8      FoodCourt  183
9   ShoppingMall  208
10           Spa  183
11        VRDeck  188
12          Name  200
13   Transported    0

In [70]:
print(list(df.dtypes))

[dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('float64'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('bool')]


In [61]:
df.isna().sum().reset_index()

index    0
0    PassengerId    0
1     HomePlanet  201
2      CryoSleep  217
3          Cabin  199
4    Destination  182
5            Age  179
6            VIP  203
7    RoomService  181
8      FoodCourt  183
9   ShoppingMall  208
10           Spa  183
11        VRDeck  188
12          Name  200
13   Transported    0

In [67]:
len(df[df['Transported']==5]) != 0

False

In [ ]:
df[df['Transported']==0]

In [11]:
df[df['HomePlanet'] == isnull()]

NameError: name 'isnull' is not defined

In [14]:
df['HomePlanet'].isnull().values

True

In [16]:
df[df['HomePlanet'].isnull()]

PassengerId HomePlanet CryoSleep     Cabin  Destination   Age    VIP  \
59       0064_02        NaN      True     E/3/S  TRAPPIST-1e  33.0  False   
113      0119_01        NaN     False     A/0/P  TRAPPIST-1e  39.0  False   
186      0210_01        NaN      True     D/6/P  55 Cancri e  24.0  False   
225      0242_01        NaN     False    F/46/S  TRAPPIST-1e  18.0  False   
234      0251_01        NaN      True    C/11/S  55 Cancri e  54.0  False   
...          ...        ...       ...       ...          ...   ...    ...   
8515     9084_01        NaN     False   E/582/P  TRAPPIST-1e  25.0  False   
8613     9194_01        NaN     False   E/603/S  55 Cancri e  53.0  False   
8666     9248_01        NaN     False  F/1792/S  55 Cancri e  38.0    NaN   
8674     9257_01        NaN     False  F/1892/P  TRAPPIST-1e  13.0  False   
8684     9274_01        NaN      True  G/1508/P  TRAPPIST-1e  23.0  False   

      RoomService  FoodCourt  ShoppingMall    Spa  VRDeck             Name  \
59            0.0        0.0           NaN    0.0     0.0      Colatz Keen   
113           0.0     2344.0           0.0   65.0  6898.0     Batan Coning   
186           0.0        0.0           NaN    0.0     0.0   Arraid Inicont   
225         313.0        1.0         691.0  283.0     0.0       Almone Sté   
234           0.0        0.0           0.0    0.0     0.0    Diphah Amsive   
...           ...        ...           ...    ...     ...              ...   
8515       1258.0        0.0          22.0   19.0     0.0        Jurs Mone   
8613          0.0     4017.0           0.0   13.0  3147.0              NaN   
8666         28.0     1208.0         973.0  207.0     0.0       Gian Perle   
8674         39.0        0.0        1085.0   24.0     0.0       Ties Apple   
8684          0.0        0.0           0.0    0.0     0.0  Chelsa Bullisey   

      Transported  
59           True  
113         False  
186          True  
225         False  
234          True  
...           ...  
8515        False  
8613        False  
8666         True  
8674        False  
8684         True  

[201 rows x 14 columns]

In [17]:
from sklearn.impute import KNNImputer

In [136]:
missing_values = ['',0,0.0,np.nan,pd.NA,None]
imputer = KNNImputer(n_neighbors=2, weights="uniform",missing_values=missing_values)
#imputer = KNNImputer(n_neighbors=2, weights="uniform")

In [137]:
imputer.fit(df[['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']])
print ('ind...',imputer.indicator_)
#arr = imputer.fit_transform(df[['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']])
arr = imputer.transform(df[['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']])

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [117]:
arr0 = np.array(df[['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']])

In [118]:
arr0

array([[3.900e+01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00],
       [2.400e+01, 1.090e+02, 9.000e+00, 2.500e+01, 5.490e+02, 4.400e+01],
       [5.800e+01, 4.300e+01, 3.576e+03, 0.000e+00, 6.715e+03, 4.900e+01],
       ...,
       [2.600e+01, 0.000e+00, 0.000e+00, 1.872e+03, 1.000e+00, 0.000e+00],
       [3.200e+01, 0.000e+00, 1.049e+03, 0.000e+00, 3.530e+02, 3.235e+03],
       [4.400e+01, 1.260e+02, 4.688e+03, 0.000e+00, 0.000e+00, 1.200e+01]])

In [119]:
arr.shape

(8693, 6)

In [120]:
arr

array([[3.900e+01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00],
       [2.400e+01, 1.090e+02, 9.000e+00, 2.500e+01, 5.490e+02, 4.400e+01],
       [5.800e+01, 4.300e+01, 3.576e+03, 0.000e+00, 6.715e+03, 4.900e+01],
       ...,
       [2.600e+01, 0.000e+00, 0.000e+00, 1.872e+03, 1.000e+00, 0.000e+00],
       [3.200e+01, 0.000e+00, 1.049e+03, 0.000e+00, 3.530e+02, 3.235e+03],
       [4.400e+01, 1.260e+02, 4.688e+03, 0.000e+00, 0.000e+00, 1.200e+01]])

In [121]:
arr0 - arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [122]:
nz = np.nonzero(arr0 - arr)

In [123]:
arr0.shape[0]

8693

In [74]:
nz

(array([   7,   10,   16, ..., 8665, 8667, 8675]),
 array([5, 3, 3, ..., 5, 3, 5]))

In [75]:
nz[0]

array([   7,   10,   16, ..., 8665, 8667, 8675])

In [79]:
6 in nz[0]

False

In [76]:
nz[0].shape

(1122,)

In [25]:
df.shape

(8693, 14)

In [68]:
lst1 = [['A','B'],['C','D']]
lst2 = [['E','F'],['G','H']]
lst1 + lst2

[['A', 'B'], ['C', 'D'], ['E', 'F'], ['G', 'H']]

In [28]:
df1 = pd.DataFrame(arr)
df1.columns = ['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']
df1.head(5)

Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0  39.0          0.0        0.0           0.0     0.0     0.0
1  24.0        109.0        9.0          25.0   549.0    44.0
2  58.0         43.0     3576.0           0.0  6715.0    49.0
3  33.0          0.0     1283.0         371.0  3329.0   193.0
4  16.0        303.0       70.0         151.0   565.0     2.0

In [113]:
a = ['FALSE', 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0, 0.0, 0.0]
b = ['FALSE', 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.00005, 0.0, 0.0, 0.0, 0.0]
a == b

False

In [114]:
lst_out = []
threshold_zerovalue = 0.0005
for i in range(len(a)):
    if (isinstance(a[i],str)):
        if (a[i]==b[i]):
            lst_out.append(0)
        else:
            lst_out.append(1)
    else:
        if (abs(a[i]-b[i])<threshold_zerovalue):
            lst_out.append(0)
        else:
            lst_out.append(1)
            

In [115]:
lst_out

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [10]:
arr = np.array([[ -0.7, np.na, 'h', 0.0, 0.0],[ 0.0, 0.0, 'h', 0.0, 0.0]])
arr

AttributeError: module 'numpy' has no attribute 'na'

In [164]:
np.isnan(arr) & np.dtype(arr)!=object

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [160]:

arr[np.isnan(arr)]=1

In [9]:
arr

NameError: name 'arr' is not defined

In [107]:
arr[(abs(arr) < 0.05) ] = 0

In [108]:
arr

array([[-0.7,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

In [22]:
arr = np.array([[None, 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0, 0.0, 0.0],['FALSE', 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0, 0.0, 0.0]])

In [26]:
arr

array([[<NA>, 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0, 0.0,
        0.0],
       ['FALSE', 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0,
        0.0, 0.0]], dtype=object)

In [24]:
arr[arr==None] = pd.NA

In [30]:
arr[0]

array([<NA>, 'Europa', 'TRAPPIST-1e', 39.0, 'FALSE', 0.0, 0.0, 0.0, 0.0,
       0.0], dtype=object)

In [31]:
arr[0][1]

'Europa'

In [39]:
a = np.array(arr[0])

In [42]:
len(a)

10

In [41]:
np.argwhere(a=='Europa')

<ipython-input-41-c79fad5eccaa>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.argwhere(a=='Europa')


array([], shape=(0, 0), dtype=int64)

In [29]:
np.where(arr[0] == 'Europa')

<ipython-input-29-270c854e97c9>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.where(arr[0] == 'Europa')


(array([], dtype=int64),)

In [27]:
df[['Age','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck']]

Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0     39.0          0.0        0.0           0.0     0.0     0.0
1     24.0        109.0        9.0          25.0   549.0    44.0
2     58.0         43.0     3576.0           0.0  6715.0    49.0
3     33.0          0.0     1283.0         371.0  3329.0   193.0
4     16.0        303.0       70.0         151.0   565.0     2.0
...    ...          ...        ...           ...     ...     ...
8688  41.0          0.0     6819.0           0.0  1643.0    74.0
8689  18.0          0.0        0.0           0.0     0.0     0.0
8690  26.0          0.0        0.0        1872.0     1.0     0.0
8691  32.0          0.0     1049.0           0.0   353.0  3235.0
8692  44.0        126.0     4688.0           0.0     0.0    12.0

[8693 rows x 6 columns]

In [43]:
df

NameError: name 'df' is not defined

In [29]:
df1.isnull().sum()

Age             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [38]:
imputer.indicator_

In [39]:
imputer.n_features_in_

6

In [40]:
imputer.feature_names_in_

AttributeError: 'KNNImputer' object has no attribute 'feature_names_in_'

In [2]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
enc = OrdinalEncoder()
X = [[pd.NA, 'YES'], ['Female', 'NO'], ['Female', 'NO']]
enc.fit(X)

AttributeError: 'bool' object has no attribute 'any'

In [4]:
enc.categories_

[array(['Female', 'Male'], dtype=object), array(['NO', 'YES'], dtype=object)]

In [5]:
[x.tolist() for x in enc.categories_] 

[['Female', 'Male'], ['NO', 'YES']]